apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: fix-permissions-and-scrub
          image: busybox:1.36
          command: [ "sh", "-c", "chown -R 10001:10001 /var/opt/mssql && rm -f /var/opt/mssql/.sqlservr.lock && rm -f /var/opt/mssql/data/*.lock" ]
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Password111!"
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc